//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreManager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ADMINUSER
    {
        [Required]
        public int ID { get; set; }
        [Required(ErrorMessage="Name not empty...")]
        public string NameUser { get; set; }
        public string RoleUser { get; set; }
        [Required(ErrorMessage = "Pass not empty...")]
        [DataType(DataType.Password)]
        public string PasswordUser { get; set; }
        [Required(ErrorMessage ="Not match with password")]
        [DataType(DataType.Password)]
        [Compare("PasswordUser")]
        public string ConfirmPass { get; set; }
        public string ErroLogin { get; set; }
    }
}
