//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITTIETDATSACH
    {
        public int MaChiTietDatSach { get; set; }
        public Nullable<int> MaSach { get; set; }
        public Nullable<int> Soluong { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<int> MADATSACH { get; set; }
    
        public virtual SACH SACH { get; set; }
        public virtual DATSACH DATSACH { get; set; }
    }
}
