//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATSACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DATSACH()
        {
            this.CHITTIETDATSACHes = new HashSet<CHITTIETDATSACH>();
        }
    
        public int MaDatSach { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        public string DiaChiGiaoHang { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITTIETDATSACH> CHITTIETDATSACHes { get; set; }
    }
}
