//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreManager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SACH()
        {
            this.BAOCAOTONKHOes = new HashSet<BAOCAOTONKHO>();
            this.CHITTIETDATSACHes = new HashSet<CHITTIETDATSACH>();
        }
    
        public int MaSach { get; set; }
        [Required(ErrorMessage = "Name not empty...")]
        public string TenSach { get; set; }
        public string Catelogy { get; set; }
        public string TacGia { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public Nullable<decimal> Price { get; set; }
        [Required(ErrorMessage = "Image not empty...")]
        public string ImageBook { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAOCAOTONKHO> BAOCAOTONKHOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITTIETDATSACH> CHITTIETDATSACHes { get; set; }
        public virtual THELOAI THELOAI { get; set; }
    }
}
