//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBBookStoreManagerEntities : DbContext
    {
        public DBBookStoreManagerEntities()
            : base("name=DBBookStoreManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_AdminUser> tbl_AdminUser { get; set; }
        public virtual DbSet<tbl_BAOCAOCONGNO> tbl_BAOCAOCONGNO { get; set; }
        public virtual DbSet<tbl_BAOCAOTONKHO> tbl_BAOCAOTONKHO { get; set; }
        public virtual DbSet<tbl_ChiTietDatSach> tbl_ChiTietDatSach { get; set; }
        public virtual DbSet<tbl_CHITIETHOADON> tbl_CHITIETHOADON { get; set; }
        public virtual DbSet<tbl_CHITIETPHIEUNHAP> tbl_CHITIETPHIEUNHAP { get; set; }
        public virtual DbSet<tbl_DatSach> tbl_DatSach { get; set; }
        public virtual DbSet<tbl_HOADON> tbl_HOADON { get; set; }
        public virtual DbSet<tbl_KHACHHANG> tbl_KHACHHANG { get; set; }
        public virtual DbSet<tbl_PHIEUNHAP> tbl_PHIEUNHAP { get; set; }
        public virtual DbSet<tbl_SACH> tbl_SACH { get; set; }
        public virtual DbSet<tbl_THELOAI> tbl_THELOAI { get; set; }
    }
}
