//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ChiTietDatSach
    {
        public int MaChiTietDatSach { get; set; }
        public Nullable<int> MaSach { get; set; }
        public Nullable<int> MaDatSach { get; set; }
        public Nullable<double> UnitPrice { get; set; }
    
        public virtual tbl_DatSach tbl_DatSach { get; set; }
        public virtual tbl_SACH tbl_SACH { get; set; }
    }
}
