//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BAOCAOCONGNO
    {
        public int MaCongNo { get; set; }
        public Nullable<int> Thang { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        public Nullable<decimal> NoDau { get; set; }
        public Nullable<decimal> NoCuoi { get; set; }
        public Nullable<decimal> NoPhatSinh { get; set; }
    
        public virtual tbl_KHACHHANG tbl_KHACHHANG { get; set; }
    }
}
