//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHIEUNHAP
    {
        public int MaChiTietPhiepNhap { get; set; }
        public Nullable<int> MaPhieuNhap { get; set; }
        public Nullable<int> SoLuongNhap { get; set; }
        public string MaSach { get; set; }
        public Nullable<decimal> DonGiaNhap { get; set; }
    
        public virtual PHIEUNHAP PHIEUNHAP { get; set; }
    }
}
