//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETGIAOHANG
    {
        public string MACTGH { get; set; }
        public string MAGH { get; set; }
        public Nullable<System.DateTime> NGAYVANCHUYEN { get; set; }
        public Nullable<System.DateTime> NGAYNHANHANG { get; set; }
        public string TRANGTHAi { get; set; }
        public Nullable<double> CHIPHIGH { get; set; }
    
        public virtual GIAOHANG GIAOHANG { get; set; }
    }
}
