//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHOADONNHAP
    {
        public string MACTHDNHAP { get; set; }
        public string MAHDNHAP { get; set; }
        public string MANL { get; set; }
        public Nullable<int> SLNHAP { get; set; }
        public Nullable<double> THANHTIEN { get; set; }
    
        public virtual HOADONNHAP HOADONNHAP { get; set; }
        public virtual NGUYENLIEU NGUYENLIEU { get; set; }
    }
}
