//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOPDONG
    {
        public string MAHD { get; set; }
        public string MANCC { get; set; }
        public string CAMKET { get; set; }
        public string DIEUKHOAN { get; set; }
        public Nullable<System.DateTime> NGAYKYKET { get; set; }
        public Nullable<System.DateTime> NGAYKETTHUC { get; set; }
    
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
    }
}
