
--TABLE NHANVIEN--
CREATE TABLE NHANVIEN
(
	MANV VARCHAR(10) NOT NULL,
	HOTEN VARCHAR(60) NOT NULL,
	NAMSINH DATE NULL,
	SDT CHAR(10) NULL,
	DIACHI NVARCHAR(100) NULL,
	EMAIL NVARCHAR(50) NULL,
	CCCD NVARCHAR(12) NULL,
	TRANGTHAI BIT NULL,
	PRIMARY KEY (MANV),
)
--TABLE HOADONBAN
CREATE TABLE HOADONBAN
(
	MAHDBAN VARCHAR(10) NOT NULL,
	Ngay DATE NULL,
	MAKH VARCHAR(10) NULL,
	MANV VARCHAR(10) NULL,
	PRIMARY KEY (MAHDBAN),
	CONSTRAINT FK_HDBAN_KHACHHANG FOREIGN KEY (MAKH) REFERENCES KHACHHANG (MAKH),
	CONSTRAINT FK_HDBAN_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV)
)
-- TABLE CHITIETHOADONBAN
CREATE TABLE CHITIETHOADONBAN
(
	MACTHDB VARCHAR(10) NOT NULL,
	MAHDBAN VARCHAR(10) NULL,
	NGAYBAN DATE NULL,
	MASP VARCHAR(10) NULL,
	SLBAN INT NULL,
	THANHTIEN FLOAT NULL,
	PRIMARY KEY (MACTHDB),
	CONSTRAINT FK_CTHDB_SANPHAM FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP),
	CONSTRAINT FK_CTHD_MAHD FOREIGN KEY (MAHDBAN) REFERENCES HOADONBAN(MAHDBAN)
)
--TABLE NHACUNGCAP
CREATE TABLE NHACUNGCAP
(
	MANCC VARCHAR(10) NOT NULL,
	TENNCC NVARCHAR(40) NOT NULL,
	LIENHE char(10) NULL,
	PRIMARY KEY (MANCC)
)
--TABLE NGUYENLIEU
CREATE TABLE NGUYENLIEU
(
	MANL VARCHAR(10) NOT NULL,
	TENNL NVARCHAR(40) NOT NULL,
	SOLUONG INT NULL,
	PRIMARY KEY (MANL),
)
--TABLE HOADONNHAP
CREATE TABLE HOADONNHAP
(
	MAHDNHAP VARCHAR(10) NOT NULL,
	NGAYNHAP DATE NULL,
	MANV VARCHAR(10) NULL,
	MANCC VARCHAR(10) NULL,
	PRIMARY KEY (MAHDNHAP),
	CONSTRAINT FK_HDNHAP_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV),
	CONSTRAINT FK_HDNHAP_NHACUNGCAP FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP (MANCC)
)
-- TABLE CHITIETHOADONBAN
CREATE TABLE CHITIETHOANHAP
(
	MACTHDNHAP VARCHAR(10) NOT NULL,
	MAHDNHAP VARCHAR(10) NULL,
	NGAYBAN DATE NULL,
	MANL VARCHAR(10) NULL,
	SLBAN INT NULL,
	THANHTIEN FLOAT NULL,
	PRIMARY KEY (MACTHDNHAP),
	CONSTRAINT FK_CTHDNHAP_NGUYENLIEU FOREIGN KEY (MANL) REFERENCES NGUYENLIEU(MANL),
	CONSTRAINT FK_CTHDNHAP_MAHDNHAP FOREIGN KEY (MAHDNHAP) REFERENCES HOADONNHAP(MAHDNHAP)
)

--TABLE HOPDONG
CREATE TABLE HOPDONG
(
	MAHD VARCHAR(10) NOT NULL,
	MANCC VARCHAR(10) NULL,
	CAMKET TEXT NULL,
	DIEUKHOAN TEXT NULL,
	NGAYKYKET DATE NULL,
	NGAYKETTHUC DATE  NULL,
	PRIMARY KEY (MAHD),
	CONSTRAINT FK_HOPDONG_NHACUNGCAP FOREIGN KEY (MANCC) references NHACUNGCAP(MANCC)
)

--TABLE ACCOUNT
CREATE TABLE ACCOUNT 
(
	ID VARCHAR(10) NOT NULL,
	USERNAME VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(10) NOT NULL,
	PHANQUYEN SMALLINT NULL,
	PRIMARY KEY (ID)
)
--TABLE BAOCAO
CREATE TABLE BAOCAO
(
	MABAOCAO VARCHAR(10) NOT NULL,
	LOAIBAOCAO NVARCHAR(30) NULL,
	NGAYTAO DATE NULL,
	TONGDOANHTHU MONEY NULL,
	GHICHU NVARCHAR(100) NULL,
	PRIMARY KEY (MABAOCAO)
)

--TABLE KHUYENMAI
CREATE TABLE KHUYENMAI
(
	MAKM VARCHAR(10) NOT NULL,
	LOAIKM NVARCHAR(20) NULL,
	CHIETKHAU FLOAT NULL,
	PRIMARY KEY (MAKM)
)
--TABLE GIAOHANG
CREATE TABLE GIAOHANG
(
	MAGH VARCHAR(10) NOT NULL,
	MAHDBAN VARCHAR(10) NULL,
	PRIMARY KEY (MAGH),
	CONSTRAINT FK_GIAOHANG_MAHDBAN FOREIGN KEY (MAHDBAN) references HOADONBAN(MAHDBAN)
)

--TABLE CHITIETGIAOHANG
CREATE TABLE CHITIETGIAOHANG
(
	MACTGH VARCHAR(10) NOT NULL,
	MAGH VARCHAR(10) NULL,
	NGAYVANCHUYEN DATE NULL,
	NGAYNHANHANG DATE NULL,
	TRANGTHAi NVARCHAR(40) NULL,
	CHIPHIGH FLOAT NULL,
	PRIMARY KEY (MACTGH),
	CONSTRAINT FK_CHITIETGIAOHANG_GIAOHANG FOREIGN KEY (MAGH) references GIAOHANG(MAGH)
)